import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { beforeEach, expect, test, vi } from 'vitest'
import { AvailabilityPage } from './availability'
import { apiRequest } from '@/lib/api'
vi.mock('@/lib/api', async original => ({ ...await original<typeof import('@/lib/api')>(), apiRequest: vi.fn() }))
const data = { timezone: 'Europe/Rome', interval_minutes: 30, start: '2026-10-05', days: 2, items: [
  { date: '2026-10-05', state: 'AVAILABLE', intervals: [
    { start: '2026-10-05T07:00:00Z', end: '2026-10-05T07:30:00Z', state: 'AVAILABLE' },
    { start: '2026-10-05T07:30:00Z', end: '2026-10-05T08:00:00Z', state: 'LIMITED' },
    { start: '2026-10-05T08:00:00Z', end: '2026-10-05T08:30:00Z', state: 'FULL' },
  ] }, { date: '2026-10-06', state: 'CLOSED', intervals: [] },
] }
beforeEach(() => { vi.resetAllMocks(); vi.mocked(apiRequest).mockResolvedValue(data) })
test('initial request is anonymous and defaults to backend-local today', async () => { render(<AvailabilityPage />); expect(screen.getByText('Loading availability…')).toBeInTheDocument(); await screen.findByText(/Business timezone: Europe\/Rome/); expect(apiRequest).toHaveBeenCalledWith('/public/availability?days=7', expect.objectContaining({ protected: false, cache: 'no-store' })); expect(screen.queryByText(/book now/i)).not.toBeInTheDocument(); expect(screen.getByText(/does not reserve a time/)).toBeInTheDocument() })
test('states and times render in business timezone with UTC offsets', async () => { render(<AvailabilityPage />); await screen.findByText(/Business timezone/); const list = within(screen.getByRole('region', { name: 'Selected day' })); expect(list.getByText(/09:00 GMT\+2/)).toHaveTextContent('Available'); expect(list.getByText(/09:30 GMT\+2.*Limited/)).toBeInTheDocument(); expect(list.getByText(/10:00 GMT\+2.*Full/)).toBeInTheDocument() })
test('selecting closed date shows no open intervals', async () => { render(<AvailabilityPage />); await screen.findByText(/Business timezone/); fireEvent.click(screen.getByRole('button', { name: /Oct 6, 2026.*Closed/ })); expect(screen.getByText('The business is closed on this date.')).toBeInTheDocument(); expect(screen.queryByRole('list')).not.toBeInTheDocument() })
test('date range form sends bounded explicit dates', async () => { render(<AvailabilityPage />); await screen.findByText(/Business timezone/); fireEvent.change(screen.getByLabelText('Start date (optional)'), { target: { value: '2026-10-25' } }); fireEvent.change(screen.getByLabelText('Days'), { target: { value: '14' } }); fireEvent.click(screen.getByText('Check dates')); await waitFor(() => expect(apiRequest).toHaveBeenCalledWith('/public/availability?days=14&start=2026-10-25', expect.anything())) })
test('error retry reloads same range and retains inputs', async () => { vi.mocked(apiRequest).mockRejectedValue(new Error('Unavailable')); render(<AvailabilityPage />); await screen.findByText('Unavailable'); expect(screen.queryByRole('region', { name: 'Selected day' })).not.toBeInTheDocument(); vi.mocked(apiRequest).mockResolvedValue(data); fireEvent.click(screen.getByText('Retry availability')); await screen.findByText(/Business timezone/); expect(apiRequest).toHaveBeenCalledTimes(2) })
test('refresh clears previous intervals while new request is pending', async () => { render(<AvailabilityPage />); await screen.findByText(/Business timezone/); vi.mocked(apiRequest).mockReturnValue(new Promise(() => {})); fireEvent.click(screen.getByText('Refresh availability')); await screen.findByText('Loading availability…'); expect(screen.queryByRole('region', { name: 'Selected day' })).not.toBeInTheDocument() })
test('empty dates response is explicit', async () => { vi.mocked(apiRequest).mockResolvedValue({ ...data, items: [] }); render(<AvailabilityPage />); await screen.findByText('No availability dates returned.'); expect(screen.queryByRole('region', { name: 'Selected day' })).not.toBeInTheDocument() })
test('repeated DST times have distinct displayed offsets', async () => { vi.mocked(apiRequest).mockResolvedValue({ ...data, start: '2026-10-25', items: [{ date: '2026-10-25', state: 'AVAILABLE', intervals: [ { start: '2026-10-25T00:00:00Z', end: '2026-10-25T00:30:00Z', state: 'AVAILABLE' }, { start: '2026-10-25T01:00:00Z', end: '2026-10-25T01:30:00Z', state: 'AVAILABLE' } ] }] }); render(<AvailabilityPage />); await screen.findByText(/02:00 GMT\+2/); expect(screen.getByText(/02:00 GMT\+1/)).toBeInTheDocument() })
test('old request is aborted and cannot replace newer availability', async () => { let resolveOld: (value: typeof data) => void = () => {}; vi.mocked(apiRequest).mockImplementationOnce(() => new Promise(resolve => { resolveOld = resolve })); render(<AvailabilityPage />); fireEvent.change(screen.getByLabelText('Start date (optional)'), { target: { value: '2026-10-06' } }); fireEvent.click(screen.getByText('Check dates')); await screen.findByText(/Business timezone/); const signal = vi.mocked(apiRequest).mock.calls[0][1]?.signal; expect(signal?.aborted).toBe(true); resolveOld({ ...data, timezone: 'UTC' }); await waitFor(() => expect(screen.queryByText(/Business timezone: UTC/)).not.toBeInTheDocument()) })
