import { useEffect, useRef, useState } from 'react'
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom'
const routes = ['Services', 'Products', 'Gallery', 'Availability', 'Contact']
const metadata: Record<string, [string, string]> = {
  '/': ['Welcome', 'Explore services, availability and contact information.'], '/services': ['Services', 'Published services, prices and durations.'], '/products': ['Products', 'Explore the public product catalog.'], '/gallery': ['Gallery', 'Photographs from the business.'], '/availability': ['Availability', 'Informational availability to help plan your visit.'], '/feedback': ['Feedback', 'Read public reviews and leave feedback.'], '/faq': ['FAQ', 'Answers to common questions before your visit.'], '/contact': ['Contact', 'Contact information, location and opening hours.'],
}
export function PublicLayout() {
  const [open, setOpen] = useState(false); const toggle = useRef<HTMLButtonElement>(null); const { pathname } = useLocation()
  useEffect(() => { setOpen(false); const [title, description] = metadata[pathname] || ['Page not found', 'Return home to explore the website.']; document.title = title; let meta = document.querySelector<HTMLMetaElement>('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.name = 'description'; document.head.append(meta) } meta.content = description }, [pathname])
  return <div className="public-site"><a className="skip-link" href="#public-main">Skip to content</a><header className="public-header" onKeyDown={event => { if (event.key === 'Escape' && open) { setOpen(false); toggle.current?.focus() } }}><Link className="public-brand" to="/">Home</Link><button ref={toggle} className="menu-toggle" aria-expanded={open} aria-controls="public-navigation" onClick={() => setOpen(!open)}>Menu</button><nav id="public-navigation" className={open ? 'public-nav open' : 'public-nav'} aria-label="Public" onKeyDown={event => { if (event.key === 'Escape') { setOpen(false); toggle.current?.focus() } }}>{routes.map(route => <NavLink key={route} to={`/${route.toLowerCase()}`}>{route}</NavLink>)}<NavLink to="/faq">FAQ</NavLink><NavLink to="/feedback">Feedback</NavLink></nav></header><main id="public-main" tabIndex={-1} className="public-main"><Outlet /></main><footer className="public-footer"><p>Explore. Plan a visit. Get in touch.</p><nav aria-label="Footer"><Link to="/faq">FAQ</Link><Link to="/feedback">Feedback</Link><Link to="/contact">Contact</Link><Link to="/login">Staff login</Link></nav></footer></div>
}
