"""Phase 1 persistent data foundation

Revision ID: 0001_phase1
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = '0001_phase1'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('instagram', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_memberships',
    sa.Column('auth_user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'STAFF', name='membership_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'auth_user_id', name='uq_membership_identity')
    )
    op.create_index(op.f('ix_admin_memberships_business_id'), 'admin_memberships', ['business_id'], unique=False)
    op.create_table('barbers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id', name='uq_barber_business_id')
    )
    op.create_index(op.f('ix_barbers_business_id'), 'barbers', ['business_id'], unique=False)
    op.create_table('business_hours',
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_business_hours_day'),
    sa.CheckConstraint('is_closed OR (opening_time IS NOT NULL AND closing_time IS NOT NULL AND closing_time > opening_time)', name='ck_business_hours_times'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'day_of_week', name='uq_business_hours_day')
    )
    op.create_index(op.f('ix_business_hours_business_id'), 'business_hours', ['business_id'], unique=False)
    op.create_table('clients',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('private_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id', name='uq_client_business_id')
    )
    op.create_index(op.f('ix_clients_business_id'), 'clients', ['business_id'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('cost_price >= 0 AND retail_price >= 0', name='ck_product_prices'),
    sa.CheckConstraint('minimum_stock >= 0', name='ck_product_minimum_stock'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id', name='uq_product_business_id'),
    sa.UniqueConstraint('business_id', 'sku', name='uq_product_sku')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_table('services',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('duration_minutes >= 0', name='ck_service_duration'),
    sa.CheckConstraint('price >= 0', name='ck_service_price'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id', name='uq_service_business_id')
    )
    op.create_index(op.f('ix_services_business_id'), 'services', ['business_id'], unique=False)
    op.create_table('appointments',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('barber_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointment_status', native_enum=False, create_constraint=True), server_default='SCHEDULED', nullable=False),
    sa.Column('appointment_notes', sa.Text(), nullable=True),
    sa.Column('visit_notes', sa.Text(), nullable=True),
    sa.Column('calculated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('final_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calculated_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('calculated_duration_minutes >= 0 AND final_duration_minutes >= 0', name='ck_appointment_duration'),
    sa.CheckConstraint('calculated_price >= 0 AND final_price >= 0', name='ck_appointment_price'),
    sa.CheckConstraint('scheduled_end > scheduled_start', name='ck_appointment_times'),
    sa.ForeignKeyConstraint(['business_id', 'barber_id'], ['barbers.business_id', 'barbers.id'], name='fk_barber_id_barbers_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id', 'client_id'], ['clients.business_id', 'clients.id'], name='fk_client_id_clients_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'id', name='uq_appointment_business_id')
    )
    op.create_index(op.f('ix_appointments_barber_id'), 'appointments', ['barber_id'], unique=False)
    op.create_index(op.f('ix_appointments_business_id'), 'appointments', ['business_id'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_table('appointment_products',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('usage_type', sa.Enum('USED', 'SOLD', name='product_usage', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_appointment_product_quantity'),
    sa.ForeignKeyConstraint(['business_id', 'appointment_id'], ['appointments.business_id', 'appointments.id'], name='fk_appointment_id_appointments_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id', 'product_id'], ['products.business_id', 'products.id'], name='fk_product_id_products_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_products_appointment_id'), 'appointment_products', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_products_business_id'), 'appointment_products', ['business_id'], unique=False)
    op.create_index(op.f('ix_appointment_products_product_id'), 'appointment_products', ['product_id'], unique=False)
    op.create_table('appointment_services',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('service_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('service_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_duration_snapshot', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('service_duration_snapshot >= 0', name='ck_snapshot_duration'),
    sa.CheckConstraint('service_price_snapshot >= 0', name='ck_snapshot_price'),
    sa.ForeignKeyConstraint(['business_id', 'appointment_id'], ['appointments.business_id', 'appointments.id'], name='fk_appointment_id_appointments_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id', 'service_id'], ['services.business_id', 'services.id'], name='fk_service_id_services_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_services_appointment_id'), 'appointment_services', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_services_business_id'), 'appointment_services', ['business_id'], unique=False)
    op.create_index(op.f('ix_appointment_services_service_id'), 'appointment_services', ['service_id'], unique=False)
    op.create_table('feedback',
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='feedback_status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_feedback_rating'),
    sa.ForeignKeyConstraint(['business_id', 'appointment_id'], ['appointments.business_id', 'appointments.id'], name='fk_appointment_id_appointments_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id', 'client_id'], ['clients.business_id', 'clients.id'], name='fk_client_id_clients_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_appointment_id'), 'feedback', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_feedback_business_id'), 'feedback', ['business_id'], unique=False)
    op.create_index(op.f('ix_feedback_client_id'), 'feedback', ['client_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('movement_type', sa.Enum('STOCK_IN', 'USED', 'SOLD', 'ADJUSTMENT', 'DAMAGED', name='movement_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'appointment_id'], ['appointments.business_id', 'appointments.id'], name='fk_appointment_id_appointments_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id', 'product_id'], ['products.business_id', 'products.id'], name='fk_product_id_products_business', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_appointment_id'), 'inventory_movements', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_business_id'), 'inventory_movements', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    # Core data belongs behind FastAPI. PostgreSQL RLS with no policies blocks
    # unprivileged Supabase Data API access; the backend DB owner still connects.
    for table in (
        "businesses", "admin_memberships", "barbers", "business_hours", "clients",
        "products", "services", "appointments", "appointment_products",
        "appointment_services", "feedback", "inventory_movements",
    ):
        op.execute(sa.text(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY'))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_business_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_appointment_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_feedback_client_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_business_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_appointment_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_appointment_services_service_id'), table_name='appointment_services')
    op.drop_index(op.f('ix_appointment_services_business_id'), table_name='appointment_services')
    op.drop_index(op.f('ix_appointment_services_appointment_id'), table_name='appointment_services')
    op.drop_table('appointment_services')
    op.drop_index(op.f('ix_appointment_products_product_id'), table_name='appointment_products')
    op.drop_index(op.f('ix_appointment_products_business_id'), table_name='appointment_products')
    op.drop_index(op.f('ix_appointment_products_appointment_id'), table_name='appointment_products')
    op.drop_table('appointment_products')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_business_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_barber_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_services_business_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_clients_business_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_business_hours_business_id'), table_name='business_hours')
    op.drop_table('business_hours')
    op.drop_index(op.f('ix_barbers_business_id'), table_name='barbers')
    op.drop_table('barbers')
    op.drop_index(op.f('ix_admin_memberships_business_id'), table_name='admin_memberships')
    op.drop_table('admin_memberships')
    op.drop_table('businesses')
    # ### end Alembic commands ###
